# .github/workflows/cd-product-catalog.yml

name: product-catalog-cd

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: src/product-catalog
          file: src/product-catalog/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/product-catalog:latest

  update-manifest:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}

      - name: Create image update branch
        run: |
          export BRANCH=auto/update-image-${{ github.sha }}
          git checkout -b $BRANCH
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.sha }}|" kubernetes/productcatalog/deploy.yaml
          git config --global user.name "mulesanket"
          git config --global user.email "sanketsp60@gmail.com"
          git add kubernetes/productcatalog/deploy.yaml
          git commit -m "[CD]: Update image to ${{ github.sha }}"
          git push origin $BRANCH

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GIT_TOKEN }}
          branch: auto/update-image-${{ github.sha }}
          base: main
          title: "[CD]: Deploy new image ${{ github.sha }}"
          body: |
            This PR updates the Kubernetes manifest with the latest image tag.
            Auto-generated by CD pipeline.
