pipeline {
    agent any

        stages {
            stage ('Code Checkout') {
                steps {
                     // Clean workspace to avoid leftover files
                     cleanWs()
                }
            }

            stage ('Test') {
                steps {
                    echo 'test'
                }
            }

            stage ('Test Test') {
                steps {
                    echo 'test test'
                }
            }
        }
}