pipeline {
    agent {

      docker {
      image 'eclipse-temurin:21-jdk'
      args "-v ${env.HOME}/.gradle:/root/.gradle:rw"
      reuseNode true
        }
    }

     options {
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '3'))
    }

    stages {
        stage ('Source Code Checkout') {
            steps {
                cleanWs()
                checkout scm
                  sh '''
                    echo "Commit SHA: $(git rev-parse HEAD)"
                    echo "Branch: $(git rev-parse --abbrev-ref HEAD)"
                    echo "Build number: ${BUILD_NUMBER}"
                    '''

                    sh 'test -f gradlew || { echo "gradlew missing"; exit 1; }'
                    stash name: 'source', includes: '**/*', excludes: '.git/**'
            }
        }

        stage ('Dependency Restore') {
            steps {
                unstash 'source'
                sh 'chmod +x gradlew'
                sh './gradlew downloadRepos'
                stash name: 'deps-ready', includes: '**/*', excludes: '.git/**'
            }
        }

        stage ('test test') {
            steps {
                echo 'test test test'
            }
        }

    }
}