pipeline {
    agent any

    stages {
        stage ('Code ') {

        }

        stage ('Source Code Checkout') {
            steps {
                cleanWs()
                checkout scm
                  sh '''
                     echo "Commit SHA: $(git rev-parse HEAD)"
                     echo "Branch: $(git rev-parse --abbrev-ref HEAD)"
                     echo "Build number: ${BUILD_NUMBER}"
                     '''
            }

        }

        stage ('') {

        }

        stage ('') {

        }


    }
}