# .github/workflows/ci-product-catalog.yml

name: product-catalog-cd

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: src/product-catalog
          file: src/product-catalog/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/product-catalog:latest

  deploy:
    runs-on: self-hosted
    needs: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image in deployment YAML and apply
        run: |
          IMAGE="${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.sha }}"
          sed -i "s|image: .*|image: $IMAGE|" kubernetes/productcatalog/deploy.yaml
          kubectl apply -f kubernetes/productcatalog/deploy.yaml

      - name: Verify deployment rollout
        run: |
          kubectl rollout status deployment/opentelemetry-demo-productcatalogservice -n opentelemetry-workspace

